### PR TITLE
[WIP] To fix #25 and #20

### LINKED ISSUE #25: 反馈一下,感谢作者的好软件
刚用上一会,然后立刻就把chrome里面的手势扩展卸了,原来单击右键出来的菜单,现在得双击,手都点累了.
言归正传,说说我用了之后的感觉,仅供参考.
1.Rules->Filter 点击Pick后,是不是将这个改成增加和删除模式会更好,而不是目前的覆盖模式.(黑白名单里面的那种模式),一不小心就要哭着重新勾选了.
2.点击Go bigger之后,按钮文字也没变,我还以为一直能大大大下去呢=.=
3.默认里面还可以把U和D分别对应Home(Fn + Left arrow) 和End(Fn + Right arrow),看起来功能会更丰满.
4.还希望能有配置导入导出功能,如果换电脑,或者进行备份/修改(测试)规则,有这个也能方便很多.

### PR DESCRIPTION
**Pull request by jiegec**
1. Done
2. Implemented by a rotate mechanism.
@CodeFalling @hstdt

P.S. The code is really hard to read. Besides, is it the right way to make a pull request within this repository? I have seen some using this way.

Waittttt I found a bug!

### CODE REVIEW

**Comment by CodeFalling** [comment]
Awesome :+1: 

Using `pull&request` inside project is not necessary(as you are a collaborator) but great.With it we could track developing of project and make it easy to do peer review.

I am so sorry for the mess code here :laughing: .

**Comment by jiegec** [comment]
BUG! Wait

**Comment by CodeFalling** [comment]
Take it easy.I just prepare to build and test from `feature/issue25` as peer review.So that's why I said using pull&request inside project is great.

Maybe we should have unit test.But I just have no idea for testing a GUI mac app.

**Comment by jiegec** [comment]
@CodeFalling Should be fixed now. I suggest adding one space after punctuations.

**Comment by jiegec** [comment]
Another BUG T_T

**Comment by jiegec** [comment]
Merged into develop.

**Pull request closed without merging**
